import { fn } from '@storybook/test';

export const ARG_TYPES = {
  isOpen: { control: 'boolean' },
  confirmLoading: { control: 'boolean' },
  title: { control: 'text' },
  closable: { control: 'boolean' },
  onOk: { action: 'onOk executed' },
  onCancel: { action: 'onCancel executed' },
  afterClose: { action: 'afterClose executed' },
  afterOpenChange: { action: 'afterOpenChange executed' },
  centered: { control: 'boolean' },
  width: { control: 'text' },
  footer: { control: 'text' },
  okText: { control: 'text' },
  okType: { control: 'text' },
  cancelText: { control: 'text' },
  maskClosable: { control: 'boolean' },
  forceRender: { control: 'boolean' },
  okButtonProps: { control: 'object' },
  cancelButtonProps: { control: 'object' },
  destroyOnClose: { control: 'boolean' },
  style: { control: 'object' },
  wrapClassName: { control: 'text' },
  maskTransitionName: { control: 'text' },
  transitionName: { control: 'text' },
  className: { control: 'text' },
  rootClassName: { control: 'text' },
  classNames: { control: 'object' },
  styles: { control: 'object' },
  getContainer: { control: 'text' },
  zIndex: { control: 'number' },
  mask: { control: 'boolean' },
  keyboard: { control: 'boolean' },
  prefixCls: { control: 'text' },
  closeIcon: { control: 'text' },
  modalRender: { control: 'text' },
  focusTriggerAfterClose: { control: 'boolean' },
  children: { control: 'text' },
  mousePosition: { control: 'object' },
  descriptionFileModal: { control: 'text' },
  titleFileModal: { control: 'text' },
  fileSettings: { control: 'object' },
} as const;

export const ARGS = {
  onOk: fn(),
  onCancel: fn(),
};
