import { fn } from '@storybook/test';

export const ARG_TYPES = {
  isAllowClear: { control: 'boolean' },
  autoFocus: { control: 'boolean' },
  className: { control: 'text' },
  format: { control: 'text' },
  popupClassName: { control: 'text' },
  preserveInvalidOnBlur: { control: 'boolean' },
  isDisabled: { control: 'boolean' },
  isDisabledDate: { control: false },
  isOpen: { control: 'boolean' },
  isReadonly: { control: 'boolean' },
  locale: { control: 'object' },
  minDate: { control: 'date' },
  maxDate: { control: 'date' },
  mode: { control: 'select', options: ['time', 'date', 'month', 'year', 'decade'] },
  needConfirm: { control: 'boolean' },
  nextIcon: { control: 'text' },
  panelRender: { control: false },
  picker: { control: 'select', options: ['date', 'week', 'month', 'quarter', 'year'] },
  placeholder: { control: 'text' },
  placement: { control: 'select', options: ['topLeft', 'topRight', 'bottomLeft', 'bottomRight'] },
  popupStyle: { control: 'object' },
  prevIcon: { control: 'text' },
  size: { control: 'select', options: ['small', 'middle', 'large'] },
  status: { control: 'select', options: ['error', 'warning'] },
  style: { control: 'object' },
  suffixIcon: { control: 'text' },
  superNextIcon: { control: 'text' },
  superPrevIcon: { control: 'text' },
  variant: { control: 'select', options: ['default', 'filled', 'outlined'] },
  onOpenChange: { control: false },
  onPanelChange: { control: false },
  allowEmpty: { control: 'object' },
  defaultPickerValue: { control: 'date' },
  defaultValue: { control: 'object' },
  id: { control: 'object' },
  pickerValue: { control: 'date' },
  presets: { control: 'object' },
  renderExtraFooter: { control: false },
  separator: { control: 'text' },
  value: { control: 'object' },
} as const;

export const DEFAULT_ARGS = {
  onCalendarChange: fn(),
  onChange: fn(),
  onFocus: fn(),
  onBlur: fn(),
};
